Just from fuzzing (seed = 0):

--------------
Forwarding dataplane event
DEBUG:FuzzSwitchImpl(1):Send PacketIn SoftSwitch(1)
DEBUG:FuzzSwitchImpl(1):Asked to send message ofp_packet_in
  header:
    version: 1
    type:    10 (OFPT_PACKET_IN)
    length:  8
    xid:     17
  buffer_id: 8
  _total_len: 0
  in_port: 1
  reason: 0
  data: EH�{@O�$ΐ�7PingPingPingPingPingPingPingPingPingPingPingPing, but not connected
---------------
Crashing switch_impl SwitchImpl(dpid=2, num_ports=1)
Round 88 completed.
2012-03-10 13:49:37,615 - openflow.topology - WARNING - Switch 00-00-00-00-00-02 disconnected, but... it's wasn't 
connected!
============== Running: ==================
python2.7 debugger.py -n -N 5 -t traces/ping_pong_fat_tree.trace 

Host names are empty, which seems odd....

But mainly:

topping Recoco Scheduler... OK
Traceback (most recent call last):
  File "debugger.py", line 169, in <module>
    simulator.simulate(panel, switch_impls, network_links, hosts, access_links, steps=args.steps)
  File "/Users/cs/Research/UCB/sdn-debugger/sts/debugger.py", line 130, in simulate
    self.loop(steps)
  File "/Users/cs/Research/UCB/sdn-debugger/sts/debugger.py", line 137, in loop
    self.trigger_events()
  File "/Users/cs/Research/UCB/sdn-debugger/sts/debugger.py", line 233, in trigger_events
    self.check_dataplane()
  File "/Users/cs/Research/UCB/sdn-debugger/sts/debugger.py", line 258, in check_dataplane
    (next_hop, next_port) = self.panel.get_connected_port(dp_event.switch, dp_event.port)
  File "/Users/cs/Research/UCB/sdn-debugger/sts/topology_generator.py", line 520, in get_connected_port
    raise RuntimeError("Node %s Port %s not in network" % (str(node), str(port)))
RuntimeError: Node SwitchImpl(dpid=7, num_ports=5) Port port_no: 5
hw_addr: 00:00:00:00:07:05

